# Generated by Django 4.2 on 2025-07-30 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TorrentDownload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("magnet_link", models.TextField(blank=True, null=True)),
                (
                    "torrent_file",
                    models.FileField(blank=True, null=True, upload_to="torrents/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("downloading", "Downloading"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                            ("paused", "Paused"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.FloatField(default=0.0)),
                ("download_speed", models.FloatField(default=0.0)),
                ("upload_speed", models.FloatField(default=0.0)),
                ("total_size", models.BigIntegerField(default=0)),
                ("downloaded_size", models.BigIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "download_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
